### ISSUE TITLE
Gestion des contacts

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Manager#1]
L'utilisateur doit pouvoir gérer une collection de contacts :
- [X] Création
- [x] Présentation
- [X] Édition
- [X] Suppression

Ces contacts ont comme attributs :
* **id** *int*
* **name** *string*
* **picture** *string*
* **emails** *array*
* **phones** *array*
* **comment** *text*

Intègrer un panel dans le dashboard pour gérer les contacts.

**Comment by wdhif** [comment]
J'ai ajouté :
- Picture (Une photo c'est toujours un plus) depuis une url
- Contracts (Pour savoir sur quoi on travail avec ce client)

Eventuellement un liens entre un client et ses factures/devis ce serait pas mal.

**Comment by WaSa42** [comment]
Les devis et factures pouront bien sûr être associés à des contacts, entreprises. Cette association se fera dans les tâches concernant les devis/factures.
