### ISSUE TITLE
Gestion des devis

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Manager#4]
L'utilisateur doit pouvoir gérer une collection de devis :
- [x] Création
- [x] Présentation
- [x] Édition
- [x] Suppression

Ces devis ont comme attributs :
* **id** *int*
* **name** *string*
* **date** *date*
* **subject** *string*
* **contact** *Contact*
* **company** *Company*
* **content** *Service*
* **comment** *text*

Les devis comportent une liste de services que l'utilisateur doit pouvoir ajouter au document :
- [x] Création
- [x] Édition
- [x] Suppression

Ces services ont comme attributs :
* **id** *int*
* **content** *string*
* **price** *int*
* **discount** *int*
* **total** *int*

Les prix totaux sont calculés à partir de l'addition des prix totaux des services.
La TVA est par défaut à 20 %.

- [x] Élaborer un template affichant correctement toutes ces informations
- [x] Permettre le téléchargement du devis en PDF

**Comment by wdhif** [comment]
Spécimen pour modèle.

[Devis Création [WORDPRESS].pdf](https://github.com/SmaltCreation/Manager/files/546/Devis.Creation.WORDPRESS.pdf)
