### ISSUE TITLE
Gestion des factures

### ISSUE THREAD

**Issue by WaSa42** [SmaltCreation/Manager#5]
L'utilisateur doit pouvoir gérer une collection de factures.
La gestion des factures doit se faire de façon REST pour les évolutions à venir :
- [x] Création
- [x] Présentation
- [x] Édition
- [x] Suppression

Ces factures héritent du devis et ont comme autres attributs :
* **estimation** *Estimation* (Devis)
* **status** *enum*
* **paid** *int* (Argent qui a été versé)

- [x]  Les factures peuvent être générée automatiquement à partir du devis.
- [x] Les factures ont le même template que les devis

Les attributs comme la date, le nom, le sujet et les commentaires seront automatiquement modifiés.
Pour un devis fait le 6 mars et une facture créée le 21 mars :

Devis | Facture
------------ | -------------
06/03/15 | 21/03/15
150306_estimation_[id] | 150321_invoice_[id]
Devis n°[id] - Création Wordpress | Facture n°[id] - Création Wordpress

- [x] Permettre le téléchargement de la facture en PDF
- [x] La facture doit pouvoir être envoyée au contact via un simple clic avec un message par défaut
  - [x] Lors de la création, passer un boolean indiquant si un email doit être envoyé automatiquement ou non à l'adresse du contact.
  - [x] Lors de la création, un message doit pouvoir être passé pour remplacer celui par défaut

**Les fonctions d'envoie de mails automatiques sont moins prioritaires. La notion de REST est cependant primordial. Le format JSON est bien sûr d'autorité.**

**Comment by arnaud-roche** [comment]
Reste à changer la date de la facture après copie du devis
